twitterAuthorization:
  debug: *****
  oauthConsumerKey: **********************
  oauthConsumerSecret: *********************************
  oauthAccessToken: ****************************
  oauthAccessTokenSecret: ***********************
