twitterAuthorization:
  debug: *****
  oauthConsumerKey: **********************
  oauthConsumerSecret: *********************************
  oauthAccessToken: ****************************
  oauthAccessTokenSecret: ***********************

logging:
  level: OFF
  loggers:
    com:
      level: *****