debug: ***** 
oauthConsumerKey: ********************** 
oauthConsumerSecret: ********************************* 
oauthAccessToken: **************************** 
oauthAccessTokenSecret: *********************** 
